# Generated by Django 5.2.7 on 2025-11-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cardapio",
            new_name="Produto",
        ),
    ]
