# Generated by Django 5.2.7 on 2025-11-07 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_rename_cardapio_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="item",
        ),
        migrations.AddField(
            model_name="pedido",
            name="encerrado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="ItensPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_through",
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="itens_through",
                        to="pedidos.produto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pedido",
            name="itens",
            field=models.ManyToManyField(
                related_name="pedidos",
                through="pedidos.ItensPedido",
                to="pedidos.produto",
            ),
        ),
    ]
