# Generated by Django 5.2.7 on 2025-11-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pedidos",
            "0003_remove_pedido_item_pedido_encerrado_em_pedido_total_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenspedido",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens_pedido",
                to="pedidos.pedido",
            ),
        ),
        migrations.AlterField(
            model_name="itenspedido",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="itens_pedido",
                to="pedidos.produto",
            ),
        ),
    ]
