# Generated by Django 5.2.7 on 2025-11-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="first_name",
            field=models.CharField(max_length=80),
        ),
    ]
