# Generated by Django 5.2.7 on 2025-11-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_alter_usuario_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="last_name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
